name: Deploy to central

on:
  release:
    types:
      - published

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        include:
#          - target: publishIosArm64PublicationToSonatypeRepository
#            os: macos-latest
          - target: :shared:publishAllPublicationsToMavenCentralRepository
            os: ubuntu-latest
          - target: :android:publishAllPublicationsToMavenCentralRepository
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v3
    - uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
#    - name: Deploy
#      uses: gradle/gradle-build-action@v3
#      with:
#        arguments: ${{ matrix.target }} --no-configuration-cache --no-daemon
#      env:
#        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
#        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
#        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MEMORY_KEY }}
#        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
#        SDK_VERSION: ${GITHUB_REF_NAME#v}
