name: Generate Docs from Dokka

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update docs
    permissions:
      contents: write
      pull-requests: write
      discussions: write
      repository-projects: write
    steps:
      -  uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Docs
        run: chmod +x gradlew && ./gradlew :android:dokkaHtml

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: android/docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Updated Docs for {msg}"