name: Verify PR

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: github-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ktlint:
    name: Run Kotlin lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
      discussions: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
  androidLint:
    name: Run Android Lint
    needs: [ ktlint ]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run Gradle
        run: ./gradlew :komoju-android-sdk:lintDebug
  swiftlint:
    runs-on: ubuntu-latest
    name: SwiftLint
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: swiftLint on ios sdk
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: komoju-ios-sdk
